### ISSUE TITLE
MIT license is used for radiant media player..still asking for licence is not available for  RMP

### ISSUE THREAD

**Issue by ReportBuilderTool** [radiantmediaplayer/BasicProject#1]

**Comment by radiantmediaplayer** [comment]
As stated in the README

BasicProject is released under MIT.

Radiant Media Player has its own license which can be found here: https://www.radiantmediaplayer.com/terms-of-service.html.

Radiant Media Player is a commercial HTML5 media player. You can request a free trial here: https://www.radiantmediaplayer.com/free-trial.html if you want to test it.
